# Netlify config (append or replace if needed)
[build]
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

# Map /api/* to Netlify Functions
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200


[build.environment]
SHARP_IGNORE_GLOBAL_LIBVIPS = "true"
